[platformio]
default_envs = esp32-s3-n16r8-real-flir

[env:esp32-s3-n16r8-demo]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem5C4C2151231
monitor_port = /dev/cu.usbmodem5C4C2151231

; ESP32-S3-WROOM N16R8 style modules use 16 MB flash and 8 MB PSRAM.
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

lib_deps =
  lovyan03/LovyanGFX@^1.2.7

extra_scripts =
  scripts/flash_backup.py

build_flags =
  -D FLIR_REAL_APP=0
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D ESP32_TOUCH_SCREEN_ENABLED=1

[env:esp32-s3-n16r8-real-flir]
extends = env:esp32-s3-n16r8-demo
build_flags =
  -D FLIR_REAL_APP=1
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D ESP32_TOUCH_SCREEN_ENABLED=1
